name: prettysize
description: Helper utility to provide pretty printed file sizes.
version: 0.1.0
homepage: https://github.com/buraktamturk/dart-prettysize
author: Burak Tamturk <buraktamturk@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
